# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 659)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.densitySlider = QtWidgets.QSlider(self.centralWidget)
        self.densitySlider.setMinimum(0)
        self.densitySlider.setMaximum(200)
        self.densitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.densitySlider.setObjectName("densitySlider")
        self.gridLayout.addWidget(self.densitySlider, 1, 3, 1, 1)
        self.sensSlider = QtWidgets.QSlider(self.centralWidget)
        self.sensSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sensSlider.setObjectName("sensSlider")
        self.gridLayout.addWidget(self.sensSlider, 3, 3, 1, 1)
        self.distSlider = QtWidgets.QSlider(self.centralWidget)
        self.distSlider.setOrientation(QtCore.Qt.Horizontal)
        self.distSlider.setObjectName("distSlider")
        self.gridLayout.addWidget(self.distSlider, 2, 3, 1, 1)
        self.showSpiral = QtWidgets.QCheckBox(self.centralWidget)
        self.showSpiral.setChecked(True)
        self.showSpiral.setObjectName("showSpiral")
        self.gridLayout.addWidget(self.showSpiral, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.exportSVG = QtWidgets.QPushButton(self.centralWidget)
        self.exportSVG.setObjectName("exportSVG")
        self.gridLayout.addWidget(self.exportSVG, 3, 0, 1, 1)
        self.showImage = QtWidgets.QCheckBox(self.centralWidget)
        self.showImage.setChecked(True)
        self.showImage.setObjectName("showImage")
        self.gridLayout.addWidget(self.showImage, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 1, 3, 1)
        self.imageLabel = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayout.addWidget(self.imageLabel, 0, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 808, 27))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.showSpiral.setText(_translate("MainWindow", "show spiral"))
        self.label.setText(_translate("MainWindow", "density"))
        self.label_3.setText(_translate("MainWindow", "sensitivity"))
        self.label_2.setText(_translate("MainWindow", "distance"))
        self.exportSVG.setText(_translate("MainWindow", "export SVG"))
        self.showImage.setText(_translate("MainWindow", "show image"))
        self.imageLabel.setText(_translate("MainWindow", "Open image to start"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

